spring:
  env: dev
  jmx:
    enabled: true

server:
  port: 8081

#management:
#  endpoint:
#    health:
#      enabled: true
#    prometheus:
#      enabled: true
#  endpoints:
#    enabled-by-default: true
#    jmx:
#      exposure:
#        include: "*"
#    web:
#      exposure:
#        include: "*"
#  metrics:
#    export:
#      prometheus:
#        enabled: true

gateway:
  version: INTERNAL_SG_STABLE_0.5.2-4